/**
 * Created By Nguyen Cong Thanh on 07/25/2020 15:57.
 *
 * Copyright intelIn 2020.
 */

const VIEW = {
  DEFAULT: 0,
  CONFIRM: 1,
  NOTIFY: 2,
  EXPIRED_TOKEN: 3,
  REMOVE_POST: 4,
  EDIT_TARGET_POST: 5,
  UPDATE_CHALLENGE_POST_RESULT: 6,
  UPDATE_USER_CHALLENGE_RESULT: 7,
  UPDATE_CHALLENGE_RESULT: 8,
  REMOVE_SUB_CHALLENGE: 9,
  APPROVE_SUB_CHALLENGE: 10,
  REMOVE_MISSION: 11,
  UPDATE_USER_CHALLENGE_MISSION: 12,
  APPLY_CHALLENGE: 13,
  END_CHALLENGE: 14,
  SEND_NOTIFICATION: 15,  //challenge
  SEND_NOTIFICATION_POST: 16,
  CREATE_NOTIFICATION: 17,
  APPLY_REWARD: 18,
  END_REWARD: 19,
  UPDATE_LIST_REQUEST: 20,
  UPDATE_SETTING: 21,
  RESET_PASSWORD: 22,
  CREATE_SETTING_MENU: 23,
  UPDATE_SETTING_MENU: 24,
  UPDATE_USER_CHALLENGE_RANK: 25,

}

class DialogEnum {
  static get VIEW() { return VIEW }
}

export default DialogEnum